name: 'PHP CS Differ'
description: 'Use PHP-CS-Fixer via GithubAction.'
author: 'mrsuh'
branding:
    icon: 'check'
    color: 'blue'
inputs:
  directory:
    description: "Directory to check"
    required: false
    default: .
runs:
    using: 'docker'
    image: 'docker://mrsuh/actions-php-cs-differ'
    args:
        - "${{ inputs.directory }}"